apiVersion: batch/v1
kind: Job
metadata:
  name: lab9
spec:
  template:
    spec:
      serviceAccount: k8sland
      containers:
        - name: lab
          image: k8sland/verifier:v1.0.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/verifier", "--u=fernand", "--l=9", "--s"]
          volumeMounts:
            - mountPath: /assets
              name: assets
      restartPolicy: Never
      volumes:
        - name: assets
          secret:
            secretName: lab9
  backoffLimit: 4
