---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sland

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sland
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs:
      - get
      - list
      - watch
      - update
      - patch

  - apiGroups: [""]
    resources: ["pods", "namespaces", "services", "deployments", "configmaps"]
    verbs:
      - get
      - list
      - watch
      - update
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sland
subjects:
  - kind: ServiceAccount
    name: k8sland
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: k8sland
  apiGroup: rbac.authorization.k8s.io
