apiVersion: v1
kind: Secret
metadata:
  name: lab5
data:
  solution.yml: CmFwaVZlcnNpb246IGFwcHMvdjEKa2luZDogRGVwbG95bWVudAptZXRhZGF0YToKICBuYW1lOiBpY29ub2ZsaXgKc3BlYzoKICByZXBsaWNhczogMQogIHNlbGVjdG9yOgogICAgbWF0Y2hMYWJlbHM6CiAgICAgIGFwcDogaWNvbm9mbGl4CiAgdGVtcGxhdGU6CiAgICBtZXRhZGF0YToKICAgICAgbGFiZWxzOgogICAgICAgIGFwcDogaWNvbm9mbGl4CiAgICBzcGVjOgogICAgICBjb250YWluZXJzOgogICAgICAgIC0gbmFtZTogaWNvbm9mbGl4CiAgICAgICAgICBpbWFnZTogcXVheS5pby9pbWhvdGVwaW8vaWNvbm9mbGl4Om1lbQogICAgICAgICAgcG9ydHM6CiAgICAgICAgICAgIC0gY29udGFpbmVyUG9ydDogNDAwMAoK
