apiVersion: batch/v1
kind: Job
metadata:
  name: configmap
spec:
  template:
    spec:
      serviceAccount: k8sland
      containers:
        - name: lab
          image: k8sland/verifier:v1.2.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/verifier", "--u=fernand", "--l=configmap", "--s"]
          volumeMounts:
            - mountPath: /assets
              name: assets
      restartPolicy: Never
      volumes:
        - name: assets
          secret:
            secretName: configmap
  backoffLimit: 4
