apiVersion: batch/v1
kind: Job
metadata:
  name: lab3
spec:
  template:
    spec:
      serviceAccount: k8sland
      containers:
        - name: lab
          image: k8sland/verifier:v0.1.2
          imagePullPolicy: IfNotPresent
          command: ["/bin/verifier", "--u=fernand", "--l=3", "--s"]
          volumeMounts:
            - mountPath: /assets
              name: assets
      restartPolicy: Never
      volumes:
        - name: assets
          secret:
            secretName: lab3
  backoffLimit: 4
