apiVersion: batch/v1
kind: Job
metadata:
  name: pod
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      serviceAccount: k8sland
      containers:
        - name: lab
          image: k8sland/verifier:v1.2.1
          imagePullPolicy: Always
          command: ["/bin/verifier", "--u=fernand", "--l=pod", "--s"]
          volumeMounts:
            - mountPath: /assets
              name: assets
      restartPolicy: Never
      volumes:
        - name: assets
          secret:
            secretName: pod
  backoffLimit: 4
