---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sland

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sland
rules:
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      [
        "pods",
        "namespaces",
        "services",
        "deployments",
        "configmaps",
        "secrets",
        "persistentvolumes",
        "persistentvolumeclaims",
      ]
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sland
subjects:
  - kind: ServiceAccount
    name: k8sland
    namespace: default
roleRef:
  kind: ClusterRole
  name: k8sland
  apiGroup: rbac.authorization.k8s.io
